---
- name: Check if http_host is empty
  assert:
    that:
      - http_host != ''
    msg: "'http_host' can not be empty"

# - name: "Verify that required string variables are defined"
#   assert:
#     that: ahs_var == ' '
#     fail_msg: "{{ ahs_var }} needs to be set for the role to work "
#     success_msg: "Required variable {{ ahs_var }} is defined"
#   loop_control:
#     loop_var: ahs_var
#   with_items:
#     - http_host

# Nginx Configuration
- name: Sets Nginx conf file
  become: yes
  template:
    src: "templates/laravel.conf"
    dest: "/etc/nginx/sites-available/{{ http_host }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Enables new site
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ http_host }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ http_host }}.conf"
    state: link
  notify: Restart Nginx
