---
- name: Check if WordPress directory exists
  stat: path={{ server_root }}{{ http_host}}
  register: check_path

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    #checksum: "sha1:{{ wp_sha1sum }}"
  become: yes
  when: not check_path.stat.exists

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    owner: alex
    group: alex
    copy: no
  become: yes
  when: not check_path.stat.exists

- name: Move WordPress install files
  command: mv /tmp/wordpress {{ server_root }}{{ http_host}}
  become: yes
  when: not check_path.stat.exists

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Add wp-config
  template:
    src: "templates/wp-config.php"
    dest: "{{ server_root }}{{ http_host}}/wp-config.php"
    owner: alex
    group: alex
    mode: 0774
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest: "{{ server_root }}{{ http_host}}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        "regexp": "define\\('DB_NAME', '(.)+'\\);",
        "line": "define('DB_NAME', '{{http_host}}');",
      }
    - {
        "regexp": "define\\('DB_USER', '(.)+'\\);",
        "line": "define('DB_USER', '{{db_user}}');",
      }
    - {
        "regexp": "define\\('DB_PASSWORD', '(.)+'\\);",
        "line": "define('DB_PASSWORD', '{{db_password}}');",
      }
  become: yes
