---
- name: Add a line to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 local-{{http_host}}.com
  become: true

- name: Create a laravel directory if it does not exist
  ansible.builtin.file:
    path: /home/alex/projects/{{http_host}}
    state: directory
    owner: alex
    group: www-data
    mode: "0775"

- name: Install laravel
  shell:
    cmd: composer create-project laravel/laravel {{http_host}}
    chdir: /home/alex/projects/
    creates: "/home/alex/projects/{{ http_host }}/public"

- name: Replace DB_DATABASE in .env conf
  ansible.builtin.lineinfile:
    path: "{{server_root}}{{http_host}}/.env"
    regexp: "^DB_DATABASE"
    line: DB_DATABASE={{http_host}}

- name: Replace DB_USERNAME in .env conf
  ansible.builtin.lineinfile:
    path: "{{server_root}}{{http_host}}/.env"
    regexp: "^DB_USERNAME"
    line: DB_USERNAME=homestead

- name: Replace DB_PASSWORD in .env conf
  ansible.builtin.lineinfile:
    path: "{{server_root}}{{http_host}}/.env"
    regexp: "^DB_PASSWORD"
    line: DB_PASSWORD=secret

- name: Replace APP_NAME in .env conf
  ansible.builtin.lineinfile:
    path: "{{server_root}}{{http_host}}/.env"
    regexp: "^APP_NAME"
    line: APP_NAME={{http_host}}

- name: Replace APP_URL in .env conf
  ansible.builtin.lineinfile:
    path: "{{server_root}}{{http_host}}/.env"
    regexp: "^APP_URL"
    line: APP_URL=http://local-{{http_host}}.com/

- name: Artisan migrate
  shell:
    cmd: php artisan migrate
    chdir: "{{server_root}}{{ http_host }}"
